import 'package:sarasotaapp/model/locationitem.dart';

class LocationInfo {
  List<LocationItem> locationitems = [
    LocationItem(
        title: 'Cape Surgery Center',
        address: '1941 Waldemere Street\nSarasota, FL 34239',
        image: 'assets/images/cape.jpg',
        mapAddress: '1941+Waldemere+Street+Sarasota+FL+34239',
        url: '9419171900',
        latitude: 27.3196016,
        longitude: -82.5331225,
        description: 'Same-day Surgery Center'),
    LocationItem(
        title: 'Heart Pavilion',
        address: '1540 S. Tamiami Trail\nSarasota, FL 34239',
        image: 'assets/images/heart.jpg',
        mapAddress: '1540+S+Tamiami+Trail+Sarasota+FL+34239',
        url: '9419176968',
        latitude: 27.3194288,
        longitude: -82.5321492,
        description: 'Outpatient Valve Clinic'),
    LocationItem(
      title: 'Bayside Center for Behavioral Health',
      address: '1650 South Osprey Avenue\nSarasota, FL, 34239',
      image: 'assets/images/bayside.jpg',
      mapAddress: '1650+South+Osprey+Avenue+Sarasota+FL+34239',
      url: '9419177760',
      latitude: 27.3186924,
      longitude: -82.5364564,
      description:
          'Mental health assessments, inpatient programs for short-term, intensive psychiatric treatment for adults, adolescents and children',
    ),
    LocationItem(
      title: 'Health Care Center & ER',
      address: '1700 S. Tamiami Trail\nSarasota, FL 34239',
      image: 'assets/images/i2.jpeg',
      mapAddress: '1700+S+Tamiami+Trail+Sarasota+FL+34239',
      url: '9419177760',
      latitude: 27.3187202,
      longitude: -82.5339287,
      description:
          '24/7 Emergency Care, outpatient radiology, laboratory and rehabilitation services, CardioPulmonary Rehabilitation, primary and speciality care physician offices',
    ),
    LocationItem(
      title: 'Health Care Center at University Parkway',
      address: '5350 University Parkway\nSarasota, FL 34243',
      image: 'assets/images/University.jpg',
      mapAddress: '5350+University+Parkway+Sarasota+FL+34243',
      url: '9419174777',
      latitude: 27.3872792,
      longitude: -82.4654344,
      description:
          'Outpatient services including Radiology/Imaging Services, Full-service Lab Testing/Bloodwork, Rehabilitation Services, Anticoagulation Clinic, Primary, Specialty, Pediatrics & Family Care.',
    ),
    LocationItem(
      title: 'Urgent Care Center at University Parkway',
      address: '5350 University Parkway\nSarasota, FL 34243',
      image: 'assets/images/universityucc.jpg',
      mapAddress: '5350+University+Parkway+Sarasota+FL+34243',
      url: '9419171234',
      latitude: 27.3872792,
      longitude: -82.4654344,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals. \nAdditional services at this location include Radiology/Imaging Services, Full-service Lab Testing/Bloodwork, Rehabilitation Services, Anticoagulation Clinic, Primary, Specialty, Pediatrics & Family Care.',
    ),
    LocationItem(
      title: 'Urgent Care Center at St. Armands Circle',
      address: '500 John Ringling Blvd,\nSarasota, FL 34236',
      image: 'assets/images/starmands.jpg',
      mapAddress: '500+John+Ringling+Blvd+Sarasota+FL+34236',
      url: '9419524750',
      latitude: 27.3190123,
      longitude: -82.5775187,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals',
    ),
    LocationItem(
      title: 'Urgent Care Center at Bee Ridge',
      address: '5590 Bee Ridge Road,\nSarasota, FL 34233',
      image: 'assets/images/beeridge.jpg',
      mapAddress: '5590+Bee+Ridge+Road+Sarasota+FL+34233',
      url: '9419174950',
      latitude: 27.2983069,
      longitude: -82.4607919,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals',
    ),
    LocationItem(
      title: 'Urgent Care Center at Stickney Point',
      address: '6331 S. Tamiami Trail\nSarasota, FL 34231',
      image: 'assets/images/stickney.jpg',
      mapAddress: '6331+S+Tamiami+Trail+Sarasota+FL+4231',
      url: '9419175678',
      latitude: 27.2627775,
      longitude: -82.5265003,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals',
    ),
    LocationItem(
      title: 'HealthFit - Powered by Sarasota Memorial',
      address: '5880 Rand Blvd\nSarasota, FL 34238',
      image: 'assets/images/healthfit.jpg',
      mapAddress: '5880+Rand+Blvd+Sarasota+FL+34238',
      url: '9419177000',
      latitude: 27.2683725,
      longitude: -82.462016,
      description:
          'Region\'s only medically integrated fitness center, offering a higher level of safety and programs focused on disease prevention, nutrition and weight loss, strength and balance, rehabilitation, and wellness.',
    ),
    LocationItem(
      title: 'Health Care Center at Clark Road',
      address: '5880 Rand Blvd\nSarasota, FL 34238',
      image: 'assets/images/clark.jpg',
      mapAddress: '5880+Rand+Blvd+Sarasota+FL+34238',
      url: '9419175111',
      latitude: 27.2684594,
      longitude: -82.4620632,
      description:
          'Outpatient services including Neuroscience Center of Excellence, Radiology Services, Full-service Laboratory Testing, Rehabilitation & Specialty Care, HealthFit – Powered by Sarasota Memorial, Primary, Pediatric & Family Care, Bariatric & Metabolic Health Center, Anticoagulation Clinic.',
    ),
    LocationItem(
      title: 'Nursing & Rehabilitation Center',
      address: '5640 Rand Blvd\nSarasota, FL 34238',
      image: 'assets/images/nursing.jpg',
      mapAddress: '5640+Rand+Blvd+Sarasota+FL+34238',
      url: '9419174950',
      latitude: 27.2638533,
      longitude: -82.4596089,
      description:
          'Short-term and Long-term Inpatient Rehabilitation, Daily Physical, Occupational and Speech, Therapies, 24-hour Nursing Care, Respiratory Therapies (24/7) and Pulmonary Conditioning.',
    ),
    LocationItem(
      title: 'Health Care Center at Heritage Harbour',
      address: '1040 River Heritage Blvd\nSarasota, FL 34212',
      image: 'assets/images/heritage.jpg',
      mapAddress: '1040+River+Heritage+Blvd+Sarasota+FL+34212',
      url: '9419176440',
      latitude: 27.4901584,
      longitude: -82.4628066,
      description:
          'Outpatient services including Radiology/Imaging Services, Full-service Lab Testing, Rehabilitation Services, Diabetes Treatment Services, Anticoagulation Clinic, Primary Family Care. \nUrgent Care Center at this location with fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals.',
    ),
    LocationItem(
      title: 'Urgent Care Center at Heritage Harbour',
      address: '1040 River Heritage Blvd\nSarasota, FL 34212',
      image: 'assets/images/heritage.jpg',
      mapAddress: '1040+River+Heritage+Blvd+Sarasota+FL+34212',
      url: '9419176440',
      latitude: 27.4901584,
      longitude: -82.4628066,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals.',
    ),
    LocationItem(
      title: 'Health Care Center at Blackburn Point',
      address: '929. S. Tamiami Trail\nSarasota, FL 34229',
      image: 'assets/images/blackburn.jpg',
      mapAddress: '929+S+Tamiami+Trail+Sarasota+FL+34229',
      url: '9419174900',
      latitude: 27.182833,
      longitude: -82.4849691,
      description:
          'Outpatient services including Radiology/Imaging Services, Full-service Laboratory Testing, Primary, Specialty, Pediatrics & Family Care, Diabetes Treatment Services, Anticoagulation Clinic, Heart Failure Clinic.',
    ),
    LocationItem(
      title: 'Health Care Center at Venice',
      address: '997 N. US 41 Bypass\nVenice, FL 34285',
      image: 'assets/images/venice.jpg',
      mapAddress: '997+N+US+41+Bypass+Venice+FL+34285',
      url: '9419524250',
      latitude: 27.1083299,
      longitude: -82.4459322,
      description:
          'Outpatient services including Radiology/Imaging Services, Full-service Lab Testing, Primary, Specialty, Pediatrics & Family Care.\nUrgent Care Center at this location with fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals.',
    ),
    LocationItem(
      title: 'Urgent Care Center at Venice',
      address: '997 N. US 41 Bypass\nVenice, FL 34285',
      image: 'assets/images/venice.jpg',
      mapAddress: '997+US+41+Bypass+Venice+FL+34285',
      url: '9419524250',
      latitude: 27.1083299,
      longitude: -82.4459322,
      description:
          'Fast treatment for non-life-threatening illnesses and injuries for patients older than 3 months, onsite imaging and laboratory tests, flu shots, other immunizations and student/sports physicals.\nAdditional services at this location include Radiology/Imaging Services, Full-service Lab Testing/Bloodwork, Anticoagulation Clinic.',
    ),
    LocationItem(
      title: 'Community Specialty Clinic',
      address: '1851 Arlington Street\nSuite 208 (second floor)',
      image: 'assets/images/NEW-CSC.jpg',
      mapAddress: '1851+Arlington+Street+Suite+208+second+floor',
      url: '9419172566',
      latitude: 27.3175158,
      longitude: -82.5348554,
      description:
          'Outpatient APPOINTMENTS ARE BY REFERRAL ONLY Sarasota Memorial\'s Community Specialty Clinic (CSC) provides specialty medical care and referral services to Sarasota County residents who are uninsured or underinsured, who demonstrate a true financial need, and who are age 18 or older',
    ),
    LocationItem(
      title: 'Health Care Center at Hillview',
      address: '1852 Hillview St.\nSarasota, FL 34239',
      image: 'assets/images/Hillview.jpg',
      mapAddress: '1852+Hillview+St+Sarasota+FL+34239',
      url: '9412629100',
      latitude: 27.3161478,
      longitude: -82.5347863,
      description:
          'Outpatient routine diagnostic, therapeutic endoscopy and colonoscopy, advanced interventional endoscopic procedures',
    ),
    LocationItem(
      title: 'Radiation Oncology Center',
      address: '5370 University Parkway\nSarasota FL 34243',
      image: 'assets/images/Radiation-Onclogy-Center.jpg',
      mapAddress: '5370+University+Parkway+Sarasota+FL+34243',
      url: '9419177575',
      latitude: 27.3863675,
      longitude: -82.4649789,
      description:
          'Outpatient by appointment only patient navigation, Oncology Counseling (emotional support), Financial counseling, External Beam Radiation Therapy, Intensity Modulated Radiation Therapy, Stereotactic Body Radiation Therapy, Image Guided Radiation Therapy, Stereotactic Radiosurgery',
    ),
    LocationItem(
      title: 'Rehabilitation Pavilion',
      address: '1700 S Tamiami Trail\nSarasota, FL 34239',
      image: 'assets/images/Rehab_locations.jpg',
      mapAddress: '1700+S+Tamiami+Trail+Sarasota+FL+34239',
      url: '9417242620',
      latitude: 27.3185613,
      longitude: -82.533929,
      description:
          'Inpatient & Outpatient Rehab Services, Comprehensive Stroke Rehabilitation, Neurological Rehabilitation, Neurological Rehabilitation, Orthopedic Rehabilitation, Cardiopulmonary Rehabilitation, Pet Therapy',
    ),
    LocationItem(
      title: 'SMH Internal Medicine – Newtown',
      address: '1825 Dr. Martin Luther King Jr. Way\nSarasota 34234',
      image: 'assets/images/Newtown.jpg',
      mapAddress: '1825+Dr+Martin+Luther+King+Jr+Way+Sarasota+34234',
      url: '9412624123',
      latitude: 27.3598546,
      longitude: -82.5364652,
      description:
          'Outpatient, appointment only Physicals, annual exams, adult vaccinations, care for chronic conditions (diabetes, high blood pressure, lupus, thyroid disease, pulmonary disease, care for acute illness (flu, pneumonia, ear, fungal infections), counseling regarding health & lifestyle concerns',
    ),
    LocationItem(
      title: 'Waldemere Medical Plaza',
      address: '1921 Waldemere Street\nSarasota, FL 34239',
      image: 'assets/images/Waldemere.jpg',
      mapAddress: '1921+Waldemere+Street+Sarasota+FL+34239',
      url: '9419176299',
      latitude: 27.3195214,
      longitude: -82.5336741,
      description:
          'Outpatient Walk-in Lab Testing, Breast Health Center & First Physicians Group offices.',
    ),
    LocationItem(
      title: 'Sarasota Memorial 3T MRI at Cattleridge',
      address: '6050 Cattleridge Blvd., Suite 102, Sarasota, FL 34232',
      image: 'assets/images/NEW-3TMRI.jpg',
      mapAddress: '6050+Cattleridge+Blvd+Suite+102+Sarasota+FL+34232',
      url: '9419524025',
      latitude: 27.3045556,
      longitude: -82.4525002,
      description: 'Outpatient Radiology Suite',
    ),
  ];
}
